/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   file-reader.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />

declare namespace LogicElements {

  /**
   * `file-reader`
   *
   * `file-reader` is an element for read files in a web browser.
   *
   * The file can be any sub-class of Blob class. That mean it can read Blobs, File objects etc.
   * The `file reader` element don't have it's own UI. It's only a helper element to us in your app's logic.
   *
   * Example:
   *
   * ```html
   * <file-reader blob="[[myFile]]" readAs="dataURL" on-file-read="myFileAsURL" auto></file-reader>
   * ```
   */
  class FileReaderComponent extends Polymer.Element {

    /**
     * A Blob to read. File object (the one you can get from the `<input type="file">`)
     * is a sub type of Blob.
     */
    blob: Blob|null;

    /**
     * Automatically read file after setting up `blob` attribute.
     * If the value of this attribute is `false` you need to call `read()` manually.
     */
    auto: boolean|null|undefined;

    /**
     * Sets how the input data should be read.
     * Result format depends on this setting.
     * Possible values are: `arrayBuffer`, `binaryString`, `dataURL`, `text`.
     */
    readAs: string|null|undefined;

    /**
     * Read-only value that is true when the data is read.
     */
    readonly loaded: boolean|null|undefined;

    /**
     * Read-only value that tracks the loading state of the data.
     */
    readonly loading: boolean|null|undefined;

    /**
     * Read-only value that indicates that the last set `blob` failed to load.
     */
    readonly error: boolean|null|undefined;

    /**
     * Current progress of file read.
     * This is set only if the browser is able to determine length of the file.
     * The value is in range from 0 to 1.
     */
    readonly progress: number|null|undefined;

    /**
     * A file encoding. Used when reading file as text.
     * If not provided UTF-8 will be assumed.
     */
    encoding: string|null|undefined;

    /**
     * Current reader.
     */
    _reader: FileReader|null|undefined;

    /**
     * Supports auto read function.
     * Called when one of `auto`, `blob` or `readAs` change and when all of them are set.
     */
    _autoChanged(auto: any, blob: any): void;

    /**
     * Read the blob.
     */
    read(): void;

    /**
     * Performs a read operation.
     */
    _read(): void;

    /**
     * Error event handler
     */
    _readError(e: any): void;

    /**
     * Load event handler
     */
    _readResult(e: any): void;

    /**
     * Abort event handler
     */
    _readAbort(): void;

    /**
     * Progress event handler.
     */
    _readProgress(e: any): void;

    /**
     * Aborts current operation.
     * If the reader is not working this method do nothing.
     * Note that the `file-abort` event is fired when this method is called.
     */
    abort(): void;
  }
}

interface HTMLElementTagNameMap {
  "file-reader": LogicElements.FileReaderComponent;
}
